newbit/newbit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

newbit/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"
urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('category/', views.category, name="category"),
    path('topic/', views.topic, name="topic"),
]

newbit/pages/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class News(models.Model):
    title = models.TextField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    category = models.TextField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    company = models.TextField(blank=True, null=True)
    date_tmp = models.IntegerField(blank=True, null=True)
    tokenized_doc = models.TextField(blank=True, null=True)
    tokenized_title = models.TextField(blank=True, null=True)
    cat_selected = models.TextField(blank=True, null=True)
    topic = models.IntegerField(blank=True, null=True)
    represent = models.IntegerField(blank=True, null=True)
    query = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'news'

# class TotalDb(models.Model):
#     title = models.TextField(blank=True, null=True)
#     date = models.TextField(blank=True, null=True)
#     category = models.TextField(blank=True, null=True)
#     content = models.TextField(blank=True, null=True)
#     company = models.TextField(blank=True, null=True)
#     date_tmp = models.BigIntegerField(blank=True, null=True)
#     tokenized_doc = models.TextField(blank=True, null=True)
#     tokenized_title = models.TextField(blank=True, null=True)
#     cat_selected = models.TextField(blank=True, null=True)
#     topic = models.BigIntegerField(blank=True, null=True)
#     represent = models.BigIntegerField(blank=True, null=True)
#     query = models.TextField(blank=True, null=True)

newbit/pages/views.py
from django.shortcuts import render, redirect, reverse
from . import newbit
from .models import News
from django.db.models import Count

# Create your views here.
def index(request):
    return render(request, 'pages/index.html', {
    })


# def result(request):
#     test = request.GET.get('q')
#     print(test)
#     return render(request, 'pages/result.html', {
#         'test': test
#     })


def dashboard(request):
    query = request.GET.get('q')
    pie = News.objects.values('cat_selected').annotate(total=Count('cat_selected')).filter(query=query)
    ts = News.objects.values('date').annotate(total=Count('date')).order_by('date_tmp').filter(query=query)
    return render(request, 'pages/dashboard.html', {
        'query': query,
        'ts': ts,
        'pie': pie,
    })


#
# def load_df(request):
#     news = News.objects.values('date').annotate(total=Count('date')).order_by('date_tmp')
#     return render(request, 'pages/charjs.html', {
#         'news': news,
#     })

def category(request):
    query = request.GET.get('q')
    context = {'query':query}

    return render(request, 'pages/category.html', context)


def topic(request):
    query = request.GET.get('q')
    context = {'query': query}

    return render(request, 'pages/topic.html', context)

newbit/pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Kaushan+Script|Dosis|Noto+Sans+KR|Libre+Baskerville|Old+Standard+TT&display=swap">
</head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    html,body{
        font-family: 'Noto Sans KR', sans-serif;
    }
    .navbar{
        height:110px;
    }
</style>
<body>

<nav id="navbar" class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
<div style="position: absolute; top:15px; left:-50px">
    <a href="/"><img class="mx-5 px-5 d-flex justify-content-start" src="/static/img/logo_black.png" height="80px" alt="" style="-webkit-filter: invert(100%)"></a>
</div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavAltMarkup">
    <div class="navbar-nav">
<!--      <a class="nav-item nav-link active mx-4" href="{% url 'pages:dashboard' %}">Home<span class="sr-only">(current)</span></a>-->
      <a class="nav-item nav-link {%if request.resolver_match.url_name == 'index'%}active{%endif%} mx-4" onclick="window.location='{% url 'pages:index' %}';">Home<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link {%if request.resolver_match.url_name == 'dashboard'%}active{%endif%} mx-4" onclick="window.location='{% url 'pages:dashboard' %}'+window.location.search;">Chart<span class="sr-only">(current)</span></a>

      <a class="nav-item nav-link {%if request.resolver_match.url_name == 'category'%}active{%endif%} mx-4" onclick="window.location='{% url 'pages:category' %}'+window.location.search;">Category</a>
      <a class="nav-item nav-link {%if request.resolver_match.url_name == 'topic'%}active{%endif%} mx-4" onclick="window.location='{% url 'pages:topic' %}'+window.location.search;"">Topic</a>
    </div>
  </div>
</nav>

<div class="row">
    <div class="col-6 mt-3">
        <div class="card">
            <div class="card-header">
                검색어
            </div>
            <div class="card-body">
               {% block query %}
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="col-6 mt-3">
        <div class="card">
            <div class="card-header">
                키워드 추가
            </div>
            <div class="card-body">
                <h5>#</h5>
            </div>
        </div>
    </div>
</div>
{% block body %}
{% endblock %}
</body>
</html>

newbit/pages/templates/pages/category.html
{% extends 'pages/base.html' %}
{% block query %}
 <form action="{% url 'pages:category' %}" method="GET" style="visiblity:hidden">
    <input type="search" style="text-align: center" autocomplete="off" name="q" id="q" placeholder="{{query}}" required/>
</form>
{% endblock %}
{% block body %}
    <div class="d-flex justify-content-center">
        <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">경제</a></li>
    <li class="breadcrumb-item"><a href="#">IT 과학</a></li>
    <li class="breadcrumb-item"><a href="#">지역</a></li>
    <li class="breadcrumb-item active" aria-current="page">사회</li>
  </ol>
</nav>
    </div>
{
    <div class="row">
        <div class="col-5 mt-3">
            <div title="3rdchart">
                <div class="container">
                    <div>
                        <canvas id="myChart3"></canvas>
                    </div>
                </div>
                <div>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
                    <script>
                        var ctx = document.getElementById('myChart3');
                        var myBarChart = new Chart(ctx, {
                            type: 'horizontalBar',
                            data: {
                                labels: ['한국일보', '전자신문', '중앙일보', '경향신문', '한겨레', '매일경제', '조선일보'],
                                datasets: [{
                                    label: '미래에셋대우 기사 빈도 시계열 그래프',
                                    data: [43, 18, 15, 14, 12, 8, 5],
                                    borderColor:[
                                    'rgba(54,162,235,0.2)',
                                    'rgba(130,162,235,0.2)',
                                    'rgba(20,162,3,0.2)',
                                    'rgba(1,50,235,0.2)',
                                    'rgba(270,162,235,0.2)',
                                    'rgba(54,300,14,0.2)',
                                    'rgba(54,15,235,0.2)',

                                    ],
                                    borderWidth: 10,
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: false,
                                        }
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div>
        </div>
        <div class="col-6 mt-3">
            <div title="2ndchart">
                <div class="container">
                    <div>
                        <canvas id="myChart4"></canvas>
                    </div>
                </div>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
                <script>
                    var ctx = document.getElementById('myChart4');
                    var myChart4 = new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
                            datasets: [{
                                label: '',
                                data: [787, 700, 632, 230, 998, 558, 453, 544,123,432,32,70],
                                borderColor:[
                                'rgba(4,456,54,0.2)'
                                ],
                                borderWidth: 10,
                            }]
                        },
                        options: {
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        beginAtZero: false,
                                    }
                                }]
                            }
                        }
                    });
                </script>
            </div>
        </div>
    </div>
<p>
    <a href="" class="d-flex justify-content-center mt-3"><h5>Topic별 대표기사</h5>
            <div>
                <p>topic1</p>
                <p>topic2</p>
                <p>topic3</p>
            </div>
    </a>
</p>
{% endblock %}

newbit/pages/templates/pages/dashboard.html
{% extends 'pages/base.html' %}
{% block head %}
<style>
.chart-container{
  max-width: 236px;
}
.wrap{
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}

</style>
{% endblock %}

{% block query %}
 <form action="{% url 'pages:dashboard' %}" method="GET" style="visiblity:hidden">
    <input type="search" style="text-align: center" autocomplete="off" name="q" id="q" placeholder="{{query}}" required/>
</form>
{% endblock %}

{% block body %}
<div class="row" style="margin-top: 30px">
    <div class="col-6 mt-3">
        <div title="1stchart">
            <div class="container">
                <div>
                    <canvas id="myChart"></canvas>
                </div>
            </div>
            <div>
                <div class="wrap">
                </div>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.3/Chart.js"></script>
                <script>
                    var ctx = document.getElementById("myChart").getContext("2d");

                    const colors = ['#f44336', ' #e91e63', '#9c27b0', '#673ab7', '#3f51b5', '#2196f3', '#03a9f4', '#00bcd4', '#009688', '#4caf50', '#8bc34a', '#cddc39', '#ffeb3b', '#ffc107', '#ff9800', '#ff5722', '#795548', '#9e9e9e', '#607d8b']
                    //const colors = ['#ffc107', '#ff9800', '#ff5722', '#795548', '#9e9e9e', '#607d8b']

                    // const colors = ['rgba(21, 176, 231, .5)',
                    //     'rgba(50, 162, 74, .5)',
                    //     'rgba(19, 47, 80,.5)',
                    //     'rgba(254, 101, 42, .5)',
                    //     'rgba(51, 51, 51,.5)']

                    const data = [
                        {% for j in pie %}
                    {{ j.total }},
                    {% endfor %}];

                    const dates = [
                        {% for j in pie %}
                    "{{ j.cat_selected }}",
                    {% endfor %}];



                    var myPieChart = new Chart(ctx,{
                        type: 'doughnut',
                        data: {
                            labels: dates,

                            datasets: [{
                                label: dates,
                                backgroundColor: colors,
                                pointBackgroundColor: colors,
                                borderColor: colors,
                                data: data,
                                borderColor: 'white',
                                borderWidth: 1,

                            }]
                        },
                        options: {
                            animation: {
                                animateScale: true
                            },
                            legend: {
                                position: 'top',
                                labels: {
                                    boxWidth: 12,
                                    fontSize: 12
                                }
                            }
                        }
                    });

                </script>
            </div>
        </div>
    </div>
    <div class="col-6 mt-3">
        <div title="2ndchart">
            <div class="container">
                <div>
                    <canvas id="myChart2"></canvas>
                </div>
            </div>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
            <script>
                var ctx2 = document.getElementById('myChart2');
                var myChart2 = new Chart(ctx2, {
                    type: 'line',
                    data: {
                        labels: [
                            {% for i in ts %}
                                "{{ i.date }}",
                            {% endfor %}
                        ],
                        datasets: [{
                            label: '{{ query }} 기사 발생 횟수',
                            data: [
                                {% for j in ts %}
                                    {{ j.total }},
                                {% endfor %}
                            ],
                            borderColor:[
                            'rgba(54,162,235,0.2)'
                            ],
                            borderWidth: 10,
                            borderWidth: 1,
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: false,
                                }
                            }]
                        }
                    }
                });
            </script>
        </div>
    </div>
</div>
<div class="d-flex justify-content-around"  style="position: relative; top:10px;">
    <a >{{ query }} 기사 카테고리 파이 그래프</a>
    <a >{{ query }} 기사 빈도 시계열 그래프 </a>

</div>
{% endblock %}

newbit/pages/templates/pages/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Kaushan+Script|Dosis|Noto+Sans+KR|Libre+Baskerville|Old+Standard+TT&display=swap">
    <title>Document</title>
    <style>



html, body {
  background: #F5BA45;
  font-family: 'Noto Sans KR', sans-serif;
}

.search {
  position: absolute;
  width: 300px;
  height: 50px;
  top: 50px;
  left: 0;
  right: 0;
  bottom: 0;
  margin: auto;
  overflow: hidden;
}
.search svg {
  width: 300px;
  -webkit-transform: translate3d(-125px, 0, 0);
          transform: translate3d(-125px, 0, 0);
  transition: 0.5s;
  pointer-events: none;
}
.search input {
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: transparent;
  border: none;
  color: #fff;
  font-family: sans-serif;
  font-size: 1.5rem;
  padding: 10px 55px 10px 10px;
  box-sizing: border-box;
  cursor: pointer;
}
.search input::-moz-selection {
  background: rgba(0, 0, 0, 0.3);
}
.search input::selection {
  background: rgba(0, 0, 0, 0.3);
}
.search input:valid, .search input:focus {
  cursor: auto;
}
.search input:valid + svg, .search input:focus + svg {
  -webkit-transform: translate3d(0, 0, 0);
          transform: translate3d(0, 0, 0);
}
.search input:focus {
  cursor: auto;
  outline: none;
}
.search input:focus + svg .path {
  stroke-dasharray: 961, 363;
  stroke-dashoffset: -363;
}
.search .path {
    stroke-dasharray: 363, 961;
    stroke-dashoffset: 0;
    stroke: #fff;
    stroke-width: 10;
    stroke-linejoin: round;
    stroke-linecap: round;
    transition: 0.5s;
}



    </style>
</head>
<body>
<div style="position: relative; top:15px; left:45px">
    <a href="/"><img class="" src="/static/img/logo_black.png" height="80px" alt="logo" style=""></a>
</div>
<div class="d-flex align-items-center justify-content-center" style="position: relative; top:150px;">
    <a class="mx-4 px-5" style="font-family: 'Libre Baskerville', serif;  font-size:35px; font-weight: bold ;text-align: center; word-spacing: 10px ;letter-spacing:3px">Build your new insight with us</a>
</div>
<div class="d-flex align-items-center justify-content-center" style="position: relative; top:200px;">

    <a class="mx-4 px-5" style="font-family: 'Old Standard TT', serif; text-align: center;  font-size:20px;">All you want is here <br>
Exploring a web new trend, and being a leader</a>

</div>
<div class="search">
<form action="{% url 'pages:dashboard' %}" method="GET" style="visiblity:hidden: ">
  <input type="search" style="text-align: center" autocomplete="off" name="q" id="q" required/>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="-20 -20 1000 150">
    <path class="path" fill="none" d="M924.4 85.2c-19.5 19.5-50.8 19.7-70.3 0-19.3-19.4-19.3-51 .3-70.6 19.5-19.5 51-19.4 70.6 0 19.3 19.7 19.3 50.8-.5 70.6l35.4 35.3H0"/>
  </svg>
</form>
</div>

<div class="d-flex align-items-center justify-content-center" style="height:900px;">
    <img class="mx-5 px-5" src="/static/img/infographic.png" height="50px" alt="" style="opacity:0.7">
    <img class="mx-5 px-5" src="/static/img/timeline (1).png" height="60px" alt="" style="opacity:0.7">
    <img class="mx-5 px-5" src="/static/img/graph.png" height="50px" alt=""style="opacity:0.7">
</div>
<div class="d-flex align-items-center justify-content-center" style="position: relative; top:-400px; right:-10px">
    <a class="mx-4 px-5" style="font-family: 'Dosis', sans-serif; font-weight: bold; font-size:20px">Categorization</a>
    <a class="mx-4 px-5" style="font-family: 'Dosis', sans-serif; font-weight: bold; font-size:20px">Timeline</a>
    <a class="mx-5 px-5" style="font-family: 'Dosis', sans-serif; font-weight: bold; font-size:20px">Visualization</a>
</div>
<div class="d-flex align-items-center justify-content-center" style="position: relative; top:-380px; right:0px">
    <a class="mx-4 px-4" style="text-align: center">카테고리 별 대표기사<br>추출하여 중복 기사 제거</a>
    <a class="mx-4 px-4" style="text-align: center">대표 기사 빈도를<br>시간순으로 출력하여<br>중요 기사 선별 기능 제공</a>
    <a class="mx-4 px-4" style="text-align: center">한 번의 클릭으로<br>기업 관련 뉴스 트렌드를<br>시각화하여 제공</a>
</div>
</body>
</html>

newbit/pages/templates/pages/topic.html
{% extends 'pages/base.html' %}
{% block query %}
 <form action="{% url 'pages:topic' %}" method="GET" style="visiblity:hidden">
    <input type="search" style="text-align: center" autocomplete="off" name="q" id="q" placeholder="{{query}}" required/>
</form>
{% endblock %}
{% block body %}
    <div class="d-flex justify-content-center">
        <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">경제</a></li>
    <li class="breadcrumb-item"><a href="#">IT 과학</a></li>
    <li class="breadcrumb-item"><a href="#">지역</a></li>
    <li class="breadcrumb-item active" aria-current="page">사회</li>
  </ol>
</nav>
    </div>

    <div class="row">
        <div class="col-6 mt-3">
            <div title="1stchart">
                <div class="container">
                    <div>
                        <canvas id="myChart"></canvas>
                    </div>
                </div>
                <div>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
                    <script>
                        var ctx = document.getElementById('myChart');
                        var myPieChart = new Chart(ctx, {
                            type: 'pie',
                            data: {
                                labels: ['1월', '2월', '3월', '4월', '5월', '6월'],
                                datasets: [{
                                    label: '미래에셋대우 기사 빈도 시계열 그래프',
                                    data: [787, 700, 632, 230, 998, 558],
                                    borderWidth: 10,
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: false,
                                        }
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div>
        </div>
        <div class="col-6 mt-3">
            <div title="2ndchart">
                <div class="container">
                    <div>
                        <canvas id="myChart2"></canvas>
                    </div>
                </div>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
                <script>
                    var ctx2 = document.getElementById('myChart2');
                    var myChart2 = new Chart(ctx2, {
                        type: 'line',
                        data: {
                            labels: ['1월', '2월', '3월', '4월', '5월', '6월'],
                            datasets: [{
                                label: '미래에셋대우 기사 빈도 시계열 그래프',
                                data: [787, 700, 632, 230, 998, 558],
                                borderWidth: 10,
                            }]
                        },
                        options: {
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        beginAtZero: false,
                                    }
                                }]
                            }
                        }
                    });
                </script>
            </div>
        </div>
    </div>
{% endblock %}